// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db_queries

import (
	"context"
)

// iteratorForCreateOutboxMessages implements pgx.CopyFromSource.
type iteratorForCreateOutboxMessages struct {
	rows                 []CreateOutboxMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateOutboxMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateOutboxMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Key,
		r.rows[0].Value,
		r.rows[0].Topic,
	}, nil
}

func (r iteratorForCreateOutboxMessages) Err() error {
	return nil
}

func (q *Queries) CreateOutboxMessages(ctx context.Context, arg []CreateOutboxMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"outbox"}, []string{"key", "value", "topic"}, &iteratorForCreateOutboxMessages{rows: arg})
}
