// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db_queries

import (
	"time"

	"github.com/google/uuid"
)

type Outbox struct {
	ID        uuid.UUID
	Key       uuid.UUID
	Value     []byte
	Topic     string
	IsRead    bool
	CreatedAt time.Time
	DeletedAt *time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiredAt time.Time
	DeletedAt *time.Time
}

type RegisterToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiredAt time.Time
	DeletedAt *time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Confirmed    bool
	HashPassword string
	DeletedAt    *time.Time
}
