services:
  http:
    build:
      context: ../
      dockerfile: build/docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080" # http 
      - "9091:9091" # Prometheus exporter

    volumes:
      - ../:/app
    env_file: ".env"
    labels:
        co.elastic.logs/enabled: true
    command: >
      sh -c 'make run-service'


  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/repository/data
    env_file: ".env"

  migrate:
    image: migrate/migrate:4
    command: -path=../migrations/ -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}" up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../migrations:/migrations:ro
    env_file: ".env"

  filebeat:
    image: elastic/filebeat:7.17.25
    command: filebeat -e -strict.perms=false
    user: root
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - "../logs:/var/log:ro"
      - "../config/filebeat.yml:/usr/share/filebeat/filebeat.yml"

  logstash:
    image: elastic/logstash:7.17.25
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ../config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 5044:5044

  elasticsearch:
    image: elastic/elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 80
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: elastic/kibana:7.17.25
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    ports:
      - 5601:5601

  grafana:
    image: grafana/grafana:8.0.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ENABLE_BASIC_AUTH=false
      - GF_SECURITY_DISABLE_LOGIN_FORM=true
    volumes:
      - ../deployments/data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.28.0
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - node_exporter

  node_exporter:
    image: prom/node-exporter:v1.1.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  jaeger:
    image: jaegertracing/all-in-one:1.26
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - "14268:14268"
      - "16686:16686"

volumes:
  postgres_data:
  redis-data:
  esdata: