services:
  http:
    container_name: http_auth_service
    build:
      context: ../
      dockerfile: build/docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    env_file: ".env"
    environment:
      - POSTGRES_ADDRESS=postgres
    labels:
        co.elastic.logs/enabled: true
    command: >
      sh -c 'make run-service'


  postgres:
    container_name: auth_db
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/repository/data
    env_file: ".env"

  migrate:
    container_name: auth_db_migrate
    image: migrate/migrate:4
    command: -path=../migrations/ -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}" up
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../migrations:/migrations:ro
    env_file: ".env"

  filebeat:
    image: elastic/filebeat:7.17.25
    command: filebeat -e -strict.perms=false
    user: root
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - "../logs:/var/log:ro"
      - "../config/filebeat.yml:/usr/share/filebeat/filebeat.yml"

  logstash:
    image: elastic/logstash:7.17.25
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ../config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - 5044:5044

  elasticsearch:
    image: elastic/elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 80
    ports:
      - 9200:9200

  kibana:
    image: elastic/kibana:7.17.25
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 80
    ports:
      - 5601:5601

volumes:
  postgres_data: