{
 "title": "AuthService",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "AVG Request Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_response_time_seconds_sum{path=~\"^/auth.*\"}[$__range])) / sum by(path) (rate(http_response_time_seconds_count{path=~\"^/auth.*\"}[$__range]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(http_requests_total{path=~\"^/auth.*\"}[$__range]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{}[$__interval]))  "
    }
   ]
  },
  {
   "title": "99th Percentile Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"Auth Service\"}[$__interval])) by (le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Successful Requests Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(http_response_status{service=\"Auth Service\",path=~\"^/auth.*\",status=~\"2..\"}[$__interval])\n/ \nrate(http_response_status{service=\"Auth Service\",path=~\"^/auth.*\"}[$__interval])\n* 100\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "95th Percentile Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket{service=\"Auth Service\"}[$__interval])) by (le))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=~\"^/auth.*\"}[$__interval])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}