mode: debug # debug, release

server:
  http:
    address: :8080
    shutdown_timeout: 5s

service:
  tokens:
    access:
      timeout: 30m
    refresh:
      timeout: 72h

logging:
  level: debug
  path: logs/auth-service.log