filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/auth-service.log
  tags: ["auth-service"]
  scan_frequency: 1s
  close_inactive: 1s
  ignore_older: 0

output.logstash:
  hosts: ["logstash:5044"]
