input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message" 
  }
}

output {
  file {
    path => "/usr/share/logstash/logs.log"
    codec => line { format => "time: %{[time]}, level: %{[level]}, msg: %{[msg]}" }
  }
  
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "auth-service-logs"
  }
}
