global: 
  scrape_interval:  1s 

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['app:8080']