#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT_PATH=$SCRIPT_DIR"/.."
ENV_FILE_PATH=$PROJECT_ROOT_PATH"/.env"


CONFIG_PATH=./config/test-config.yaml
POSTGRES_ADDRESS=localhost
POSTGRES_PORT=54321
POSTGRES_USER=test_user
POSTGRES_PASSWORD=test_password
POSTGRES_DB=test_db
POSTGRES_SSLMODE=disable
SECRET_KEY=test_secret_key

REDIS_ADDRESS=localhost
REDIS_PORT=63790
REDIS_USER=test_user 
REDIS_PASSWORD=test_password 
REDIS_USER_PASSWORD=test_user_password 
REDIS_DB=0

echo "CONFIG_PATH=$CONFIG_PATH" > $ENV_FILE_PATH
echo "POSTGRES_ADDRESS=$POSTGRES_ADDRESS" >> $ENV_FILE_PATH
echo "POSTGRES_PORT=$POSTGRES_PORT" >> $ENV_FILE_PATH
echo "POSTGRES_USER=$POSTGRES_USER" >> $ENV_FILE_PATH
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $ENV_FILE_PATH
echo "POSTGRES_DB=$POSTGRES_DB" >> $ENV_FILE_PATH
echo "POSTGRES_SSLMODE=$POSTGRES_SSLMODE" >> $ENV_FILE_PATH
echo "SECRET_KEY=$SECRET_KEY" >> $ENV_FILE_PATH

echo "REDIS_ADDRESS=$REDIS_ADDRESS" >>  $ENV_FILE_PATH
echo "REDIS_PORT=$REDIS_PORT" >>  $ENV_FILE_PATH
echo "REDIS_USER=$REDIS_USER" >>  $ENV_FILE_PATH
echo "REDIS_PASSWORD=$REDIS_PASSWORD" >>  $ENV_FILE_PATH
echo "REDIS_USER_PASSWORD=$REDIS_USER_PASSWORD" >>  $ENV_FILE_PATH
echo "REDIS_DB=$REDIS_DB" >>  $ENV_FILE_PATH